### PR TITLE
Remove the shebang in index.js and release v1.4.4

### LINKED ISSUE #41: Error building with Webpack.
I get the error:

`SyntaxError: Unexpected character '#' (1:0)` on index.js.

That line is most likely unneeded?

### PR DESCRIPTION
**Pull request by d00rman**
Fixes #41

### CODE REVIEW

**Comment by d00rman** [comment]
cc @mvolz

**Comment by mvolz** [comment]
-1

There's another one in lib/index.js as well :D

**Comment by d00rman** [comment]
@mvolz {{done}}

**Comment by mvolz** [comment]
Published on npm and tagged as v1.4.4

**Pull request merged**
