### PR TITLE
Updates packages, fix tests

### PR DESCRIPTION
**Pull request by mvolz**
* Update packages (preq, bluebird, mocha, cheerio)
* Fix name of test to be more descriptive
* Restore two tests that were previously failing due to website being
down
* Minor fix for cheerio update in jsonLd due to non-backwards
compatible changes

### CODE REVIEW

**Comment by d00rman** [comment]
@mvolz LGTM, but GH says there are conflicts. Could you rebase the patch on top of master, please?

**Comment by mvolz** [comment]
Does it? It says "This branch has no conflicts with the base branch" ? for me...

**Comment by d00rman** [comment]
@mvolz if you switch to "rebase and merge" (the preferred way), it does. This means that you simply need to `git rebase origin/master` locally on your branch and then `git push -f`

**Comment by mvolz** [comment]
done

**Pull request merged**
