### PR TITLE
Add Twitter Support

### PR DESCRIPTION
**Pull request by blydro**
Follows the twitter guidelines as outlined [here](https://dev.twitter.com/cards/markup).

Closes [T148835](https://phabricator.wikimedia.org/T148835)

### CODE REVIEW

**Comment by mvolz** [comment]
Looks good!

Just a few cursory comments:

* Should probably increment version in package.json (see semvar.org)
* Did you look into reusing the exports.parseBase function? Twitter is relatively uncomplicated so it should work for it. 
* It would be ideal if you could squash these 4 commits into one commit.

**Comment by mvolz** [comment]
It looks like some of the tests are timing out (I rechecked and it was a different one this time.) You may want to increase the timeout length and see if that fixes is it so the tests pass. Might just be some random latency upstream somewhere.

**Comment by blydro** [comment]
I looked at using the parseBase function, but it was too difficult to implement as getContent would have to either return a string or an object based on the whether the property should be nested or not, which would require parsing all of the property info again. In addition, the logic for amending an existing nested property would get even more convoluted. If there is a clean solution I'm not seeing please let me know, but based on some experimentation it looks like not using parseBase is simpler.

I've made all the other changes and cleaned things up a bit. The unit test is still timing out even though I bumped the timeout to 50 (!) seconds.

**Comment by mvolz** [comment]
I'll look into it some more, but it's consistently only failing with Node
.10 and passing on more updated versions. We use node 4.6 in production so
losing .10 is not a big deal. Maybe we can pin in to newer node versions in
using the engine key in package.json. Or maybe try using a different url
than the aftenposten one. This is the problem with doing tests on live
websites, they sometimes don't perform well :P. Although it did *really*
quite badly (5 minutes to run tests!) with node .10 so it can't all be the
website's fault!

**Comment by mvolz** [comment]
The espn one is "failing" for me locally because it redirects to the espn.co.uk url. Maybe just match a few parameters inside the nesting to make sure they're in there?

**Comment by blydro** [comment]
I've changed the test from espn to the guardian, and I've tested it from the us and the uk both running node .10 and everything seems to pass.

**Comment by mvolz** [comment]
Great! Needs rebase against the master branch, but looks good otherwise.

**Pull request merged**
